# Generated by Django 4.2.29 on 2026-04-17 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="csv_uploads/%Y/%m/")),
                ("description", models.CharField(max_length=200)),
                ("uploaded_by", models.CharField(max_length=100)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("students_created", models.IntegerField(default=0)),
                ("students_updated", models.IntegerField(default=0)),
                ("errors", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-upload_date"],
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "target_branches",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated branch codes, e.g. CS,IT. Leave blank for all.",
                        max_length=50,
                    ),
                ),
                (
                    "target_semesters",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated semester numbers, e.g. 1,2,3. Leave blank for all.",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("CS", "Computer Science"),
                            ("IT", "Information Technology"),
                            ("EC", "Electronics & Communication"),
                            ("ME", "Mechanical"),
                            ("CE", "Civil"),
                            ("EE", "Electrical"),
                        ],
                        max_length=2,
                    ),
                ),
                ("semester", models.IntegerField()),
                ("subject_code", models.CharField(max_length=10)),
                ("subject_name", models.CharField(max_length=100)),
                ("credits", models.IntegerField(default=4)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "unique_together": {("branch", "semester", "subject_code")},
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("registration_number", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "branch",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CS", "Computer Science"),
                            ("IT", "Information Technology"),
                            ("EC", "Electronics & Communication"),
                            ("ME", "Mechanical"),
                            ("CE", "Civil"),
                            ("EE", "Electrical"),
                        ],
                        max_length=2,
                    ),
                ),
                ("semester", models.IntegerField(blank=True, null=True)),
                ("year_of_admission", models.IntegerField(blank=True, null=True)),
                ("father_name", models.CharField(blank=True, max_length=100)),
                ("mother_name", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("is_password_changed", models.BooleanField(default=False)),
                (
                    "auto_generated_password",
                    models.CharField(blank=True, max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SemesterResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.IntegerField()),
                ("internal_marks", models.IntegerField(default=0)),
                ("external_marks", models.IntegerField(default=0)),
                ("total_marks", models.IntegerField(default=0)),
                ("grade", models.CharField(blank=True, max_length=2)),
                ("is_pass", models.BooleanField(default=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.studentprofile",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.subject",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "semester", "subject")},
            },
        ),
        migrations.CreateModel(
            name="InternalExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("CA1", "Class Assessment 1"),
                            ("CA2", "Class Assessment 2"),
                            ("CA3", "Class Assessment 3"),
                            ("MSE", "Mid Semester Exam"),
                            ("ASSIGNMENT", "Assignment"),
                            ("ATTENDANCE", "Attendance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("marks_obtained", models.IntegerField()),
                ("max_marks", models.IntegerField()),
                ("exam_date", models.DateField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.studentprofile",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.subject",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "subject", "exam_type")},
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("is_present", models.BooleanField(default=True)),
                ("marked_by", models.CharField(default="System", max_length=50)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.studentprofile",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.subject",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "subject", "date")},
            },
        ),
    ]
