# Generated by Django 4.2.29 on 2026-04-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="credentials_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="current_password",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
