# Generated by Django 4.2.29 on 2026-04-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_facultyprofile_bio_facultyprofile_can_enter_marks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="branch",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CS", "Computer Science"),
                    ("CE", "Civil"),
                    ("EC", "Electronics"),
                    ("ME", "Mechanical"),
                    ("EE", "Electrical"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="branch",
            field=models.CharField(
                choices=[
                    ("CS", "Computer Science"),
                    ("CE", "Civil"),
                    ("EC", "Electronics"),
                    ("ME", "Mechanical"),
                    ("EE", "Electrical"),
                ],
                max_length=2,
            ),
        ),
    ]
