# Generated by Django 4.2.29 on 2026-04-19 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0008_alter_studentprofile_branch_alter_subject_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notices",
                to="students.facultyprofile",
            ),
        ),
    ]
